spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false        #通过eureka.client.registerWithEureka：false
    fetch-registry: false               #和fetchRegistry：false来表明自己是一个eureka server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eukera
  server:
    enable-self-preservation: false    #关闭eureka自我保护